/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "CLERK_SECRET_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DB_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DB_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PUBLIC_CLERK_PUBLISHABLE_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Web": {
      "type": "sst.aws.SvelteKit"
      "url": string
    }
    "croppedHeadshots": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "seedContestants": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "seedCorrectCouples": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "seedMarriedCouples": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
  }
}
